### ISSUE TITLE
Date and Location on event page are on the same line

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/stanford_decanter#11]
**For theme version stanford_decanter 1.x-2.0.0-alpha2** 

Configuration of flex display pushes date and location to be on the same line without margins - these should be two separate lines

July 20, 2011 - 5:00pmLocation: Cubberley Library large instruction room (Note: food and drink are not permitted in Cubberley)

https://opensource.su.domains/events/drupallers-drop-help-15
<img width="1186" alt="Screenshot 2024-11-19 at 4 01 59 PM" src="https://github.com/user-attachments/assets/fb3a64da-4296-424e-9d7d-847d47587e71">

**Comment by ronan** [comment]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/38b4c8ce-389c-461c-828d-c8a062062af4">

This is fixed in 2.x-dev

We should come up with a list of field names and icons for future fields:

<img width="319" alt="image" src="https://github.com/user-attachments/assets/f4f194c6-073c-4609-8a91-7bddf85ddf3b">
 (from https://events.stanford.edu/event/lessons_carols_2023)
